### ISSUE TITLE
Clarification on Project 3

### ISSUE THREAD

**Issue by lotzha** [stefanbund/SDLC-GITHUB#5]
We are kind of confused on what exactly what need to write for project 3, can you post some clarifications? Cause the only available source is the Project 3 outline. Are we suppose to write a tactic strategy paper for the application we developed? Do we need to implement project 2 into it? 
Thank you

**Comment by stefanbund** [comment]
Please begin with your conclusions from project two. This will create the strategic outline for the application. Then go forward with the bullets outlined within our assignment document, on the hub.

From Stefan

**Comment by stefanbund** [comment]
Go ahead and ask those questions where you need clarification.

From Stefan
